spring.application.name=springboot-backend-chat

websocket.allowed-origins=http://localhost:4200

spring.mongodb.uri = mongodb://localhost:27017/springboot_chat

logging.level.org.springframework.data.mongodb.core.Mongotemplate=debug

# spring.security.oauth2.resourceserver.jwt.public-key-location=http://localhost:8080/realms/vmseca
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/vmseca/protocol/openid-connect/certs